### ISSUE TITLE
alluxio2.9.2 start with error java.lang.NoSuchMethodError: io.netty.util.concurrent.SingleThreadEventExecutor

### ISSUE THREAD

**Issue by 3qianlian** [Alluxio/alluxio#17140]
**Alluxio Version:**
alluxio2.9.2
Maven3.6.3 
Jdk1.8

**Describe the bug**
Compile using the 2.9.2 version of alloxio. The compilation was successful, but an error was reported during startup.

**To Reproduce**
Compilation command：
mvn -T 2C -am clean install -Dmaven.javadoc.skip=true -DskipTests -Dlicense.skip=true -Dcheckstyle.skip=true -Dfindbugs.skip=true -Pmesos -Pufs-hadoop-3 -Dufs.hadoop.version=3.3.1 -Dmaven.buildNumber.revisionOnScmFailure=2.9.2

Start command：
  alluxio-start.sh all SudoMount

**Expected behavior**
Startup error:

Exception in thread "main" java.lang.NoSuchMethodError: io.netty.util.concurrent.SingleThreadEventExecutor.<init>(Lio/netty/util/concurrent/EventExecutorGroup;Ljava/util/concurrent/Executor;ZLjava/util/Queue;Lio/netty/util/concurrent/RejectedExecutionHandler;)V
        at io.netty.channel.SingleThreadEventLoop.<init>(SingleThreadEventLoop.java:65)
        at io.netty.channel.epoll.EpollEventLoop.<init>(EpollEventLoop.java:90)
        at io.netty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:151)
        at io.netty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:35)
        at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
        at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
        at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47)
        at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59)
        at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:112)
        at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:99)
        at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:76)
        at alluxio.util.network.NettyUtils.createEventLoop(NettyUtils.java:71)
        at alluxio.grpc.GrpcChannelPool.lambda$acquireNetworkEventLoop$4(GrpcChannelPool.java:295)
        at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1853)
        at alluxio.grpc.GrpcChannelPool.acquireNetworkEventLoop(GrpcChannelPool.java:274)
        at alluxio.grpc.GrpcChannelPool.createManagedChannel(GrpcChannelPool.java:198)
        at alluxio.grpc.GrpcChannelPool.lambda$acquireChannel$1(GrpcChannelPool.java:121)
        at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1853)
        at alluxio.grpc.GrpcChannelPool.acquireChannel(GrpcChannelPool.java:94)
        at alluxio.grpc.GrpcChannelBuilder.build(GrpcChannelBuilder.java:92)
        at alluxio.util.network.NetworkAddressUtils.pingService(NetworkAddressUtils.java:721)
        at alluxio.common.RpcPortHealthCheckClient.isServing(RpcPortHealthCheckClient.java:66)
        at alluxio.worker.job.AlluxioJobWorkerMonitor.main(AlluxioJobWorkerMonitor.java:46)

**Comment by LuQQiu** [comment]
@JiamingMai any thoughts?
